# Generated by Django 4.2.7 on 2024-02-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='سربرگ')),
                ('name', models.CharField(max_length=30, verbose_name='نام محصول')),
                ('description', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(default='', null=True)),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
