# Generated by Django 4.2.7 on 2024-02-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='link_img',
            field=models.CharField(max_length=50, null=True, verbose_name='لینک محصول'),
        ),
    ]
