# Generated by Django 4.2.7 on 2024-02-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='db',
            options={'verbose_name': 'اطلاعات ورود', 'verbose_name_plural': 'اطلاعات ورود'},
        ),
        migrations.AddField(
            model_name='db',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
